spring.application.name=identity-service
#server.port=8081 -> identity-service.properties
spring.datasource.url=${IDENTITY_DB_URL:jdbc:postgresql://localhost:5432/identity}
spring.datasource.username=${IDENTITY_DB_USERNAME:identity}
spring.datasource.password=${IDENTITY_DB_PASSWORD:identity}
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#management.endpoints.web.exposure.include=health,info -> application.properties
#management.endpoint.health.show-details=never -> application.properties
#services.customer.base-url=${CUSTOMER_SERVICE_BASE_URL:http://localhost:8082} -> identity-service.properties
security.jwt.issuer=${JWT_ISSUER:http://virtual-bank.local}
security.jwt.audience=${JWT_AUDIENCE:virtual-bank-api}
#security.jwt.access-token-ttl=${JWT_ACCESS_TTL:PT15M} -> identity-service.properties
#security.jwt.refresh-token-ttl=${JWT_REFRESH_TTL:P7D} -> identity-service.properties
security.jwt.public-key-location=${JWT_PUBLIC_KEY:classpath:keys/jwt-public.pem}
security.jwt.private-key-location=${JWT_PRIVATE_KEY:classpath:keys/jwt-private.pem}
#security.password.bcrypt-strength=${BCRYPT_STRENGTH:12} -> identity-service.properties


#eureka.client.enabled=true
#eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
#eureka.instance.prefer-ip-address=true

spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.enabled=true
