CREATE USER identity WITH PASSWORD 'identity';
CREATE DATABASE identity OWNER identity;

CREATE USER customer WITH PASSWORD 'customer';
CREATE DATABASE customer OWNER customer;

CREATE USER banking WITH PASSWORD 'banking';
CREATE DATABASE banking OWNER banking;

CREATE USER transfer WITH PASSWORD 'transfer';
CREATE DATABASE transfer OWNER transfer;

REVOKE CONNECT ON DATABASE identity FROM PUBLIC;
REVOKE CONNECT ON DATABASE customer FROM PUBLIC;
REVOKE CONNECT ON DATABASE banking FROM PUBLIC;
REVOKE CONNECT ON DATABASE transfer FROM PUBLIC;

GRANT CONNECT ON DATABASE identity TO identity;
GRANT CONNECT ON DATABASE customer TO customer;
GRANT CONNECT ON DATABASE banking TO banking;
GRANT CONNECT ON DATABASE transfer TO transfer;
