spring.application.name=api-gateway
server.port=8080
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=never
management.endpoint.gateway.access=read-only

spring.cloud.gateway.server.webflux.routes[0].id=identity-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://identity-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates=Path=/api/v1/auth/**


spring.cloud.gateway.server.webflux.routes[1].id=banking-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://banking-service:8083
spring.cloud.gateway.server.webflux.routes[1].predicates=Path=/api/v1/accounts/**