spring.application.name=banking-service
server.port=8083
spring.datasource.url=${BANKING_DB_URL:jdbc:postgresql://localhost:5434/banking}
spring.datasource.username=${BANKING_DB_USERNAME:banking}
spring.datasource.password=${BANKING_DB_PASSWORD:banking}
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
services.customer.base-url=${CUSTOMER_SERVICE_BASE_URL:http://localhost:8082}
security.jwt.issuer=${JWT_ISSUER:http://virtual-bank.local}
security.jwt.audience=${JWT_AUDIENCE:virtual-bank-api}
security.jwt.public-key-location=${JWT_PUBLIC_KEY:classpath:keys/jwt-public.pem}
spring.jpa.open-in-view=false
