spring.application.name=customer-service
server.port=8082
spring.datasource.url=${CUSTOMER_DB_URL:jdbc:postgresql://localhost:5433/customer}
spring.datasource.username=${CUSTOMER_DB_USERNAME:customer}
spring.datasource.password=${CUSTOMER_DB_PASSWORD:customer}
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
security.jwt.issuer=${JWT_ISSUER:http://virtual-bank.local}
security.jwt.audience=${JWT_AUDIENCE:virtual-bank-api}
security.jwt.public-key-location=${JWT_PUBLIC_KEY:classpath:keys/jwt-public.pem}
