spring.application.name=transfer-service
server.port=8084
spring.datasource.url=${TRANSFER_DB_URL:jdbc:postgresql://localhost:5435/transfer}
spring.datasource.username=${TRANSFER_DB_USERNAME:transfer}
spring.datasource.password=${TRANSFER_DB_PASSWORD:transfer}
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
services.banking.base-url=${BANKING_SERVICE_BASE_URL:http://localhost:8083}
services.exchange-rate.base-url=${EXCHANGE_RATE_SERVICE_BASE_URL:http://localhost:8085}
security.jwt.issuer=${JWT_ISSUER:http://virtual-bank.local}
security.jwt.audience=${JWT_AUDIENCE:virtual-bank-api}
security.jwt.public-key-location=${JWT_PUBLIC_KEY:classpath:keys/jwt-public.pem}
spring.jpa.open-in-view=false

#Eureka
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true


management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents

resilience4j.circuitbreaker.instances.exchangeRateService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.exchangeRateService.sliding-window-size=4
resilience4j.circuitbreaker.instances.exchangeRateService.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.exchangeRateService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.exchangeRateService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.exchangeRateService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.exchangeRateService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.exchangeRateService.ignore-exceptions[0]=org.springframework.web.client.HttpClientErrorException
