spring.application.name=transfer-service
server.port=8084
spring.datasource.url=${TRANSFER_DB_URL:jdbc:postgresql://localhost:5435/transfer}
spring.datasource.username=${TRANSFER_DB_USERNAME:transfer}
spring.datasource.password=${TRANSFER_DB_PASSWORD:transfer}
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
services.banking.base-url=${BANKING_SERVICE_BASE_URL:http://localhost:8083}
services.exchange-rate.base-url=${EXCHANGE_RATE_SERVICE_BASE_URL:http://localhost:8085}
security.jwt.issuer=${JWT_ISSUER:http://virtual-bank.local}
security.jwt.audience=${JWT_AUDIENCE:virtual-bank-api}
security.jwt.public-key-location=${JWT_PUBLIC_KEY:classpath:keys/jwt-public.pem}
spring.jpa.open-in-view=false
