spring.application.name=exchange-rate-service
server.port=8085
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
exchange-rate.provider.api-key=${EXCHANGE_RATE_API_KEY:}
exchange-rate.provider=${EXCHANGE_RATE_PROVIDER:MOCK}
security.jwt.issuer=${JWT_ISSUER:http://virtual-bank.local}
security.jwt.audience=${JWT_AUDIENCE:virtual-bank-api}
security.jwt.public-key-location=${JWT_PUBLIC_KEY:classpath:keys/jwt-public.pem}


eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true