spring.application.name=eureka-server
server.port=8761
# Eureka no se registrara a si mismo
eureka.client.register-with-eureka=false
# Eureka no debe descargar el registro de servicios desde otro server Eureka
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,inf
# health -> endpoint que indica el estado de la aplicacion
# /actuator/health
# {"status": "UP"}

# info -> muestra informacion descriptiva sobre la aplicacion
# /actuator/info
# { status, components, disk }

management.endpoint.health.show-details=never